apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  labels:
    app: {{ .Values.app.name }}
{{- include "yuga-planner.labels" . | nindent 4 }}
data:
  JAVA_HOME: {{ .Values.env.java.home | quote }}
  PATH: {{ .Values.env.java.path | quote }}
