apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  labels:
    app: {{ .Values.app.name }}
{{- include "yuga-planner.labels" . | nindent 4 }}
type: Opaque
stringData:
  # These values will be populated from environment variables during deployment
  NEBIUS_API_KEY: {{ .Values.secrets.nebiusApiKey | quote }}
  NEBIUS_MODEL: {{ .Values.secrets.nebiusModel | quote }}
  MODAL_TOKEN_ID: {{ .Values.secrets.modalTokenId | quote }}
  MODAL_TOKEN_SECRET: {{ .Values.secrets.modalTokenSecret | quote }}
  HF_MODEL: {{ .Values.secrets.hfModel | quote }}
  HF_TOKEN: {{ .Values.secrets.hfToken | quote }}
