apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  labels:
    app: {{ .Values.app.name }}
{{- include "yuga-planner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
    protocol: {{ .Values.service.protocol }}
    name: {{ .Values.container.name }}
  selector:
    app: {{ .Values.app.name }}
{{- include "yuga-planner.selectorLabels" . | nindent 4 }}
